export const permissionDefinitions = [
  ['course.read', '查看授权课程', false],
  ['course.manage', '维护授权课程', false],
  ['course.admin', '机构教学安排', false],
  ['learning.use', '个人学习与作答', false],
  ['question.manage', '题库与试卷管理', false],
  ['assessment.manage', '作业考试发布', false],
  ['assessment.grade', '授权教学批阅', false],
  ['grade.revise', '成绩复核改分', true],
  ['communication.read', '交流阅读', false],
  ['communication.write', '交流发言', false],
  ['communication.moderate', '机构内容治理', false],
  ['file.upload', '业务附件上传', false],
  ['users.manage', '账号与基础角色分配', false],
  ['org.manage', '机构组织管理', false],
  ['org.platform', '平台机构管理', false],
  ['roles.manage', '权限模板维护', false],
  ['grants.manage', '独立敏感授权', false],
  ['analysis.read', '业务统计', false],
  ['analysis.sensitive', '教学成绩统计明细', true],
  ['data.export', '个人资料和成绩导出', true],
  ['settings.org', '机构配置', false],
  ['settings.platform', '安全与平台配置', false],
  ['audit.read', '审计与运行记录', false],
] as const;
export const roleDefinitions: Record<string, { name: string; description: string; permissions: string[] }> = {
  STUDENT: {
    name: '学生',
    description: '本人学习记录与当前课程、班级',
    permissions: ['course.read', 'learning.use', 'communication.read', 'communication.write', 'file.upload'],
  },
  TEACHER: {
    name: '教师',
    description: '当前被授权的课程和教学班',
    permissions: [
      'course.read',
      'course.manage',
      'question.manage',
      'assessment.manage',
      'assessment.grade',
      'grade.revise',
      'communication.read',
      'communication.write',
      'file.upload',
      'analysis.read',
      'data.export',
    ],
  },
  ADMIN: {
    name: '机构管理员',
    description: '当前机构账号、组织与运行管理',
    permissions: [
      'course.admin',
      'users.manage',
      'org.manage',
      'communication.read',
      'communication.moderate',
      'analysis.read',
      'analysis.sensitive',
      'data.export',
      'settings.org',
      'audit.read',
    ],
  },
  SUPER_ADMIN: {
    name: '超级管理员',
    description: '明确授权的平台管理；敏感权限仍需要独立限时授予',
    permissions: [
      'course.admin',
      'users.manage',
      'org.manage',
      'org.platform',
      'roles.manage',
      'grants.manage',
      'communication.read',
      'communication.moderate',
      'analysis.read',
      'analysis.sensitive',
      'data.export',
      'settings.org',
      'settings.platform',
      'audit.read',
    ],
  },
};
