import type { MajorTemplate, SubjectTemplate } from './academics.types';
export const academicSubjects: SubjectTemplate[] = [
  { id: 'subject-philosophy', name: '哲学', description: '论证、逻辑、伦理与批判思维。' },
  { id: 'subject-economics', name: '经济学', description: '经济模型、金融数学与市场分析。' },
  { id: 'subject-law', name: '法学与社会治理', description: '法律论证、社会研究、公共议题与证据分析。' },
  { id: 'subject-education', name: '教育学', description: '教学设计、教育研究与运动表现分析。' },
  { id: 'subject-literature', name: '文学与语言', description: '阅读、写作、外语、翻译与新闻传播。' },
  { id: 'subject-history', name: '历史学', description: '史料整理、年代脉络、来源比较与历史论证。' },
  { id: 'subject-science', name: '理学', description: '数学、物理、化学、生物与地理的模型和实验。' },
  { id: 'subject-engineering', name: '工学', description: '计算机、电子、机械、土木、建筑与环境工程。' },
  { id: 'subject-agriculture', name: '农学', description: '农业水量、遗传、食品与生态系统学习。' },
  {
    id: 'subject-medicine',
    name: '医学与健康科学',
    description: '解剖、生理、单位换算与模拟观察记录的课程练习。',
  },
  {
    id: 'subject-military',
    name: '军事学与国防教育',
    description: '国防教育中的历史研究、地理测量与后勤管理基础。',
  },
  { id: 'subject-management', name: '管理学', description: '会计、项目、供应链、营销与服务管理。' },
  { id: 'subject-art', name: '艺术学', description: '设计、音乐、作品集与视觉表达。' },
  {
    id: 'subject-interdisciplinary',
    name: '交叉学科',
    description: '数据科学、认知研究、数字人文与跨专业项目。',
  },
  {
    id: 'subject-general',
    name: '通识与自主学习',
    description: '自由笔记、研究计划与可自主组合的学习工具。',
  },
];
const major = (
  id: string,
  name: string,
  subject: string,
  description: string,
  modules: string[],
): MajorTemplate => ({
  id: `major-${id}`,
  name,
  subjectId: `subject-${subject}`,
  description,
  moduleIds: [
    ...new Set([
      ...modules,
      'research-planning',
      'study-notebook',
      ...(['biology', 'ecology', 'agronomy', 'horticulture', 'animal-science'].includes(id)
        ? ['population-genetics']
        : []),
    ]),
  ],
});
export const academicMajors: MajorTemplate[] = [
  major(
    'computer-science',
    '计算机科学与技术',
    'engineering',
    '从算法与数据库到网络与软件设计，练习可运行的实现与工程思考。',
    ['algorithms', 'sql-lab', 'subnet-lab', 'software-design', 'data-science', 'cybersecurity-lab'],
  ),
  major(
    'software-engineering',
    '软件工程',
    'engineering',
    '结合需求、数据模型、测试与迭代计划完成软件项目。',
    ['algorithms', 'sql-lab', 'software-design', 'project-planning', 'design-contrast'],
  ),
  major('artificial-intelligence', '人工智能', 'engineering', '从矩阵、概率与数据分析理解建模过程和评估。', [
    'matrix-lab',
    'probability-lab',
    'statistics-lab',
    'data-science',
    'algorithms',
  ]),
  major(
    'data-science',
    '数据科学与大数据技术',
    'interdisciplinary',
    '练习数据查询、预处理、描述统计和回归分析。',
    ['sql-lab', 'data-science', 'statistics-lab', 'matrix-lab', 'probability-lab'],
  ),
  major(
    'cybersecurity',
    '网络空间安全',
    'engineering',
    '理解子网、基础密码变换和软件安全需求，练习防御性思考。',
    ['subnet-lab', 'cybersecurity-lab', 'algorithms', 'software-design'],
  ),
  major('network-engineering', '网络工程', 'engineering', '用CIDR、网络地址和连通性工具学习网络规划。', [
    'subnet-lab',
    'algorithms',
    'project-planning',
    'digital-logic',
  ]),
  major(
    'information-systems',
    '信息管理与信息系统',
    'management',
    '将数据库查询、业务指标与需求设计结合起来。',
    ['sql-lab', 'software-design', 'business-analysis', 'project-planning'],
  ),
  major(
    'electrical-engineering',
    '电气工程及其自动化',
    'engineering',
    '分析电阻网络、功率、逻辑电路与动力学。',
    ['circuit-lab', 'digital-logic', 'physics-motion', 'matrix-lab'],
  ),
  major(
    'electronic-information',
    '电子信息工程',
    'engineering',
    '练习电路、逻辑、信号所需的数学与网络基础。',
    ['circuit-lab', 'digital-logic', 'calculus-lab', 'subnet-lab'],
  ),
  major('telecommunications', '通信工程', 'engineering', '组合网络地址、概率、数据和电路分析工具。', [
    'subnet-lab',
    'probability-lab',
    'circuit-lab',
    'matrix-lab',
  ]),
  major('automation', '自动化', 'engineering', '从动力学、线性代数和电路模型建立系统分析习惯。', [
    'physics-motion',
    'matrix-lab',
    'circuit-lab',
    'data-science',
  ]),
  major('robotics', '机器人工程', 'engineering', '把机构运动、矩阵运算、逻辑和项目设计结合起来。', [
    'mechanics-lab',
    'matrix-lab',
    'digital-logic',
    'software-design',
  ]),
  major('mechanical-engineering', '机械工程', 'engineering', '学习齿轮传动、简支梁与物理运动的理想模型。', [
    'mechanics-lab',
    'civil-beam',
    'physics-motion',
    'scale-lab',
  ]),
  major('aerospace', '航空航天工程', 'engineering', '用运动、结构、数值积分与项目管理练习工程建模。', [
    'physics-motion',
    'civil-beam',
    'calculus-lab',
    'project-planning',
  ]),
  major('civil-engineering', '土木工程', 'engineering', '练习结构静力、尺度与项目进度的基础计算。', [
    'civil-beam',
    'scale-lab',
    'project-planning',
    'statistics-lab',
  ]),
  major('architecture', '建筑学', 'engineering', '从空间任务书、尺度换算与视觉表达组织设计过程。', [
    'architecture-studio',
    'scale-lab',
    'design-contrast',
    'design-portfolio',
  ]),
  major('urban-planning', '城乡规划', 'engineering', '以空间测量、调查、设计任务书与项目计划分析规划议题。', [
    'geography-lab',
    'social-research',
    'architecture-studio',
    'project-planning',
  ]),
  major(
    'environmental-engineering',
    '环境工程',
    'engineering',
    '练习混合水体质量守恒、农业水量和环境数据分析。',
    ['environment-lab', 'chemistry-solution', 'statistics-lab', 'geography-lab'],
  ),
  major('chemical-engineering', '化学工程与工艺', 'engineering', '结合反应配平、溶液计算与质量平衡。', [
    'chemistry-balance',
    'chemistry-solution',
    'environment-lab',
    'calculus-lab',
  ]),
  major('materials', '材料科学与工程', 'engineering', '使用化学、力学和统计工具整理材料实验。', [
    'chemistry-balance',
    'chemistry-solution',
    'civil-beam',
    'statistics-lab',
  ]),
  major('biomedical-engineering', '生物医学工程', 'interdisciplinary', '联系生物结构、信号数学与工程测量。', [
    'anatomy-quiz',
    'circuit-lab',
    'data-science',
    'genetics-lab',
  ]),
  major('mathematics', '数学与应用数学', 'science', '练习矩阵、微积分、概率和数学论证。', [
    'matrix-lab',
    'calculus-lab',
    'probability-lab',
    'algorithms',
  ]),
  major('statistics', '统计学', 'science', '理解样本、描述统计、线性拟合与概率分布。', [
    'statistics-lab',
    'probability-lab',
    'data-science',
    'social-research',
  ]),
  major('physics', '物理学', 'science', '分析运动、电路、积分和线性模型。', [
    'physics-motion',
    'circuit-lab',
    'calculus-lab',
    'matrix-lab',
  ]),
  major('chemistry', '化学', 'science', '从元素守恒、化学式和浓度单位练习定量化学。', [
    'chemistry-balance',
    'chemistry-solution',
    'statistics-lab',
  ]),
  major('biology', '生物科学', 'science', '通过遗传模型、结构知识与实验设计开展学习。', [
    'genetics-lab',
    'anatomy-quiz',
    'statistics-lab',
    'psychology-design',
  ]),
  major('geography', '地理科学', 'science', '用经纬度距离、空间比例和环境模型理解空间问题。', [
    'geography-lab',
    'scale-lab',
    'environment-lab',
    'social-research',
  ]),
  major('ecology', '生态学', 'science', '联系遗传、环境质量守恒与田间水量。', [
    'genetics-lab',
    'environment-lab',
    'agriculture-lab',
    'statistics-lab',
  ]),
  major('clinical-medicine', '临床医学', 'medicine', '使用课程级解剖练习、文献阅读与模拟观察整理知识。', [
    'anatomy-quiz',
    'clinical-reading',
    'statistics-lab',
    'pharmacology-units',
  ]),
  major('nursing', '护理学', 'medicine', '练习解剖基础、观察记录与单位核算，不涉及真实临床处置。', [
    'anatomy-quiz',
    'nursing-observation',
    'pharmacology-units',
    'clinical-reading',
  ]),
  major('pharmacy', '药学', 'medicine', '练习单位量纲、配制数学与化学基础。', [
    'pharmacology-units',
    'chemistry-solution',
    'chemistry-balance',
    'clinical-reading',
  ]),
  major('public-health', '预防医学与公共卫生', 'medicine', '用统计、证据阅读与社会调查理解群体研究。', [
    'statistics-lab',
    'probability-lab',
    'clinical-reading',
    'social-research',
  ]),
  major('medical-laboratory', '医学检验技术', 'medicine', '结合单位、浓度和数据质量复核实验计算。', [
    'pharmacology-units',
    'chemistry-solution',
    'statistics-lab',
    'anatomy-quiz',
  ]),
  major('dentistry', '口腔医学', 'medicine', '整理结构基础、证据与模拟课程案例。', [
    'anatomy-quiz',
    'clinical-reading',
    'nursing-observation',
    'statistics-lab',
  ]),
  major('rehabilitation', '康复治疗学', 'medicine', '以运动测量、结构知识和课程证据练习为主。', [
    'anatomy-quiz',
    'sports-analysis',
    'physics-motion',
    'clinical-reading',
  ]),
  major('agronomy', '农学', 'agriculture', '练习田间水量、遗传与生态数据。', [
    'agriculture-lab',
    'genetics-lab',
    'environment-lab',
    'statistics-lab',
  ]),
  major('horticulture', '园艺', 'agriculture', '结合水量管理、遗传和尺度设计形成实验记录。', [
    'agriculture-lab',
    'genetics-lab',
    'scale-lab',
    'design-portfolio',
  ]),
  major('forestry', '林学', 'agriculture', '使用空间测量、生态质量守恒与调查记录。', [
    'geography-lab',
    'agriculture-lab',
    'environment-lab',
    'social-research',
  ]),
  major('animal-science', '动物科学', 'agriculture', '练习遗传比例、成分数据与实验设计。', [
    'genetics-lab',
    'food-science',
    'statistics-lab',
    'research-planning',
  ]),
  major('food-science', '食品科学与工程', 'agriculture', '练习配料质量、能量核算、浓度与质量管理数据。', [
    'food-science',
    'chemistry-solution',
    'statistics-lab',
    'inventory-lab',
  ]),
  major('economics', '经济学', 'economics', '推导供需均衡、弹性与经营模型。', [
    'economics-lab',
    'business-analysis',
    'statistics-lab',
    'finance-lab',
  ]),
  major('finance', '金融学', 'economics', '练习复利、现金流折现与概率统计。', [
    'finance-lab',
    'probability-lab',
    'statistics-lab',
    'economics-lab',
  ]),
  major('international-trade', '国际经济与贸易', 'economics', '结合经营指标、物流、经济模型与语言表达。', [
    'economics-lab',
    'business-analysis',
    'inventory-lab',
    'language-lab',
  ]),
  major('accounting', '会计学', 'management', '练习复式记账、试算平衡与基础财务数学。', [
    'accounting-ledger',
    'finance-lab',
    'business-analysis',
  ]),
  major('financial-management', '财务管理', 'management', '连接现金流、会计、经营指标与库存分析。', [
    'finance-lab',
    'accounting-ledger',
    'business-analysis',
    'inventory-lab',
  ]),
  major(
    'business-management',
    '工商管理',
    'management',
    '利用项目网络、营销漏斗、成本和研究工作台分析经营。',
    ['project-planning', 'business-analysis', 'economics-lab', 'social-research'],
  ),
  major('marketing', '市场营销', 'management', '练习转化漏斗、盈亏平衡、媒体核验与调研设计。', [
    'business-analysis',
    'media-literacy',
    'social-research',
    'statistics-lab',
  ]),
  major('logistics', '物流管理', 'management', '练习经济订货量、再订货点与关键路径。', [
    'inventory-lab',
    'project-planning',
    'business-analysis',
    'geography-lab',
  ]),
  major('human-resources', '人力资源管理', 'management', '用研究设计、项目与规范论证梳理人力资源议题。', [
    'social-research',
    'psychology-design',
    'project-planning',
    'legal-reasoning',
  ]),
  major('public-administration', '公共管理', 'management', '整理公共议题、证据、利益相关者与项目执行。', [
    'social-research',
    'legal-reasoning',
    'project-planning',
    'media-literacy',
  ]),
  major('tourism', '旅游管理', 'management', '在给定任务资料中设计行程、预算与服务方案。', [
    'tourism-planning',
    'geography-lab',
    'business-analysis',
    'language-lab',
  ]),
  major('law', '法学', 'law', '以事实、争点、规则来源与双方论证构建案例分析。', [
    'legal-reasoning',
    'philosophy-argument',
    'writing-studio',
    'social-research',
  ]),
  major('sociology', '社会学', 'law', '练习研究问题、抽样、访谈与统计分析。', [
    'social-research',
    'statistics-lab',
    'psychology-design',
    'media-literacy',
  ]),
  major('social-work', '社会工作', 'law', '以虚构案例整理需求、资源与支持计划。', [
    'social-research',
    'psychology-design',
    'legal-reasoning',
    'project-planning',
  ]),
  major('political-science', '政治学与行政学', 'law', '比较来源、分析论证、组织社会研究。', [
    'philosophy-argument',
    'social-research',
    'history-research',
    'media-literacy',
  ]),
  major('education', '教育学', 'education', '组织教学目标、活动、评价与教育研究设计。', [
    'education-design',
    'psychology-design',
    'social-research',
    'statistics-lab',
  ]),
  major('primary-education', '小学教育', 'education', '围绕年龄适宜目标设计课堂任务与形成性评价。', [
    'education-design',
    'writing-studio',
    'language-lab',
    'design-contrast',
  ]),
  major('physical-education', '体育教育', 'education', '核算配速、运动表现数据并组织教学。', [
    'sports-analysis',
    'education-design',
    'statistics-lab',
    'physics-motion',
  ]),
  major('psychology', '心理学', 'science', '从变量、对照、混淆因素与统计设计理解研究。', [
    'psychology-design',
    'statistics-lab',
    'probability-lab',
    'social-research',
  ]),
  major('chinese-literature', '汉语言文学', 'literature', '练习文本细读、证据引用、论证与写作。', [
    'literature-reading',
    'writing-studio',
    'philosophy-argument',
    'history-research',
  ]),
  major('english', '英语', 'literature', '练习学术词汇、翻译策略与结构化写作。', [
    'language-lab',
    'translation-studio',
    'writing-studio',
  ]),
  major('translation', '翻译', 'literature', '记录源文、译文、术语、目的和修订理由。', [
    'translation-studio',
    'language-lab',
    'writing-studio',
    'media-literacy',
  ]),
  major('journalism', '新闻学', 'literature', '梳理五要素、来源可信性与交叉核验。', [
    'media-literacy',
    'writing-studio',
    'social-research',
    'history-research',
  ]),
  major('communications', '传播学', 'literature', '结合媒体核验、调查设计与传播指标。', [
    'media-literacy',
    'social-research',
    'business-analysis',
    'statistics-lab',
  ]),
  major('history', '历史学', 'history', '以史料元数据、年代、来源比较和论证构建研究记录。', [
    'history-research',
    'literature-reading',
    'philosophy-argument',
    'geography-lab',
  ]),
  major('archaeology', '考古学', 'history', '练习资料整理、空间比例与来源论证。', [
    'history-research',
    'scale-lab',
    'geography-lab',
    'research-planning',
  ]),
  major('philosophy', '哲学', 'philosophy', '分解主张、前提、推理、反例与回应。', [
    'philosophy-argument',
    'legal-reasoning',
    'literature-reading',
    'writing-studio',
  ]),
  major('visual-design', '视觉传达设计', 'art', '核对色彩对比、设计目标和作品集中的过程证据。', [
    'design-contrast',
    'design-portfolio',
    'architecture-studio',
    'media-literacy',
  ]),
  major('industrial-design', '工业设计', 'art', '结合尺度、机构基础、设计任务书与作品集。', [
    'design-portfolio',
    'scale-lab',
    'mechanics-lab',
    'architecture-studio',
  ]),
  major('digital-media', '数字媒体艺术', 'art', '在视觉、软件需求、叙事与作品集之间建立联系。', [
    'design-contrast',
    'design-portfolio',
    'software-design',
    'writing-studio',
  ]),
  major('music', '音乐学', 'art', '用十二平均律频率和音程工具学习声音关系。', [
    'music-lab',
    'education-design',
    'design-portfolio',
    'history-research',
  ]),
  major('fine-arts', '美术学', 'art', '记录作品观察、形式分析、创作过程与修订。', [
    'design-portfolio',
    'design-contrast',
    'literature-reading',
    'history-research',
  ]),
  major(
    'defense-education',
    '国防教育与军事基础',
    'military',
    '开展课程级历史、地理和后勤学习，不包含武器与作战操作。',
    ['history-research', 'geography-lab', 'inventory-lab', 'project-planning'],
  ),
  major('digital-humanities', '数字人文', 'interdisciplinary', '连接文本、数据库、统计与来源研究。', [
    'literature-reading',
    'sql-lab',
    'data-science',
    'history-research',
  ]),
  major('cognitive-science', '认知科学', 'interdisciplinary', '组合实验设计、概率、数据与哲学论证。', [
    'psychology-design',
    'data-science',
    'probability-lab',
    'philosophy-argument',
  ]),
  major('general', '自主学习与通识', 'general', '自由组合学习板块，记录目标、练习与复盘。', [
    'writing-studio',
    'statistics-lab',
    'language-lab',
    'study-notebook',
  ]),
];
