/** Curated original learning paths. Progress is based on accepted formal submissions. */
export const algorithmPlans = [
  {
    id: 'first-steps',
    title: '零基础编程起步',
    description: '从输入输出到数组与字符串，建立读题、实现、验证的完整习惯。',
    level: '入门',
    estimatedDays: 7,
    chapters: [
      {
        title: '熟悉判题流程',
        description: '先跑样例，再补边界，最后正式提交。',
        problemIds: ['sum-of-two', 'array-maximum'],
      },
      {
        title: '掌握数组与字符串',
        description: '练习双指针、计数和基础查询，明确下标与边界。',
        problemIds: ['palindrome-word', 'two-sum-indices', 'range-sum'],
      },
    ],
  },
  {
    id: 'linear-patterns',
    title: '数组与字符串常用技巧',
    description: '用不变量理解二分、栈、滑动窗口和区间扫描。',
    level: '基础',
    estimatedDays: 10,
    chapters: [
      {
        title: '查询与匹配',
        description: '理解有序性和后进先出如何减少重复工作。',
        problemIds: ['first-position', 'balanced-brackets'],
      },
      {
        title: '连续区间',
        description: '区分连续子数组、滑动窗口与区间合并的状态。',
        problemIds: ['maximum-subarray', 'longest-unique-window', 'merge-intervals'],
      },
    ],
  },
  {
    id: 'dp-divide',
    title: '动态规划与分治进阶',
    description: '从状态定义出发，推导转移、初值、遍历顺序与复杂度。',
    level: '进阶',
    estimatedDays: 7,
    chapters: [
      {
        title: '动态规划',
        description: '练习计数型与最优化型状态，解释每一项转移的来源。',
        problemIds: ['grid-paths', 'minimum-coins'],
      },
      {
        title: '分治与合并',
        description: '将跨区间贡献嵌入归并过程，并注意大整数。',
        problemIds: ['inversion-count'],
      },
    ],
  },
  {
    id: 'trees-graphs',
    title: '树与图专题',
    description: '从遍历、连通性和最短路走向最小生成树，区分路径最短与全图连接总权最小。',
    level: '进阶',
    estimatedDays: 16,
    chapters: [
      {
        title: '遍历与连通性',
        description: '学习队列、显式栈与访问标记，避免重复访问。',
        problemIds: ['binary-tree-depth', 'island-count', 'connected-components'],
      },
      {
        title: '依赖与带权路径',
        description: '区分拓扑顺序与最短距离，选择合适的数据结构。',
        problemIds: ['course-order', 'shortest-path'],
      },
      {
        title: '全图连接与贪心',
        description: '组合边排序与并查集，用安全边和交换论证理解最小生成树。',
        problemIds: ['minimum-spanning-tree'],
      },
    ],
  },
];

algorithmPlans.push(
  {
    id: 'number-foundations',
    title: '数论与整数计算',
    description: '练习整除、筛法、组合和快速幂，识别大整数与取模的计算边界。',
    level: '基础',
    estimatedDays: 12,
    chapters: [
      {
        title: '整除与质因数',
        description: '从欧几里得算法到质数、因数和欧拉函数。',
        problemIds: [
          'euclidean-gcd',
          'common-period',
          'prime-check',
          'prime-count',
          'divisor-count',
          'factorial-zeros',
          'coprime-count',
        ],
      },
      {
        title: '计数与快速计算',
        description: '理解进制分解、倍增、组合数和博弈不变量。',
        problemIds: ['base-conversion', 'modular-power', 'pascal-choice', 'fibonacci-mod', 'nim-winning'],
      },
    ],
  },
  {
    id: 'array-toolbox',
    title: '数组统计与数据结构',
    description: '把计数、前缀、差分与有序候选结合，掌握线性扫描与动态查询。',
    level: '基础',
    estimatedDays: 20,
    chapters: [
      {
        title: '统计与去重',
        description: '区分值集合和位置集合，处理重复值与严格条件。',
        problemIds: [
          'unique-values',
          'second-distinct',
          'majority-ballot',
          'sorted-deduplicate',
          'rotate-array',
          'mex-number',
          'pair-difference',
        ],
      },
      {
        title: '连续段与批量修改',
        description: '识别可抵消的前缀状态和单调移动的窗口。',
        problemIds: [
          'odd-subarrays',
          'zero-sum-subarrays',
          'product-except-self',
          'shortest-positive-window',
          'fixed-window-total',
          'range-increments',
          'range-xor',
        ],
      },
      {
        title: '动态候选与查询',
        description: '从栈队列到单调结构、堆和树状数组。',
        problemIds: [
          'stack-journal',
          'queue-journal',
          'next-greater-index',
          'window-maximum',
          'histogram-area',
          'priority-dispatch',
          'kth-ranked',
          'dynamic-range-sum',
        ],
      },
    ],
  },
  {
    id: 'strings-and-greedy',
    title: '字符串与贪心证明',
    description: '先理解文本结构，再用交换论证、扫描线和二分答案解决调度问题。',
    level: '进阶',
    estimatedDays: 20,
    chapters: [
      {
        title: '匹配与镜像',
        description: '区分连续片段与子序列，并解释前缀回退为何正确。',
        problemIds: [
          'anagram-labels',
          'run-length-encode',
          'run-length-decode',
          'shortest-string-period',
          'pattern-occurrences',
          'longest-palindrome-length',
          'palindrome-substring-count',
          'subsequence-check',
          'caesar-shift',
          'minimum-rotation',
          'word-frequency',
          'bracket-insertions',
        ],
      },
      {
        title: '贪心与单调可行性',
        description: '为每种局部选择找出保持最优的理由。',
        problemIds: [
          'minimum-value-gap',
          'median-movement',
          'nonoverlap-events',
          'minimum-rooms',
          'deadline-reward',
          'merge-batch-cost',
          'two-person-carriers',
          'tolerance-matching',
          'factory-target-time',
          'contiguous-capacity',
          'minimum-jumps',
          'missing-subset-sum',
        ],
      },
    ],
  },
  {
    id: 'dynamic-programming-lab',
    title: '动态规划系统练习',
    description: '围绕状态语义、重复使用限制、枚举顺序和区间依赖建立完整训练。',
    level: '进阶',
    estimatedDays: 24,
    chapters: [
      {
        title: '序列与编辑',
        description: '辨清连续、不连续、严格递增和编辑操作。',
        problemIds: ['increasing-subsequence', 'common-subsequence', 'edit-distance', 'nonadjacent-value'],
      },
      {
        title: '背包与计数',
        description: '用循环顺序表达0/1、无限使用与有序无序的区别。',
        problemIds: [
          'zero-one-knapsack',
          'ordered-coin-ways',
          'unordered-coin-ways',
          'subset-target',
          'integer-partitions',
          'rod-cut-value',
        ],
      },
      {
        title: '路径与区间状态',
        description: '由最后一步或最后切分推导转移，使用滚动数组。',
        problemIds: [
          'bounded-hop-cost',
          'grid-minimum-cost',
          'largest-one-square',
          'matrix-chain-cost',
          'palindromic-subsequence',
          'end-picking-game',
        ],
      },
    ],
  },
  {
    id: 'graph-and-tree-lab',
    title: '图论与树形状态进阶',
    description: '涵盖有向可达性、拓扑计数、低链值、匹配、流量和树上换根。',
    level: '进阶',
    estimatedDays: 30,
    chapters: [
      {
        title: '遍历与路径',
        description: '选择BFS、0-1 BFS、Floyd或Bellman-Ford，并明确适用权值。',
        problemIds: [
          'unweighted-distance',
          'bipartite-check',
          'directed-reach-count',
          'strong-component-count',
          'dag-longest-edges',
          'dag-path-count',
          'all-pairs-routes',
          'zero-one-distance',
          'negative-cycle-check',
        ],
      },
      {
        title: '图的结构与优化',
        description: '理解割边割点、欧拉条件、增广路和残量网络。',
        problemIds: [
          'bridge-count',
          'articulation-count',
          'euler-trail-check',
          'bipartite-matching',
          'maximum-network-flow',
        ],
      },
      {
        title: '树上查询与决策',
        description: '用父节点顺序代替深递归，推导倍增与换根。',
        problemIds: [
          'tree-diameter',
          'rooted-subtree-sizes',
          'lowest-common-ancestor',
          'tree-independent-count',
          'tree-distance-sums',
          'tree-maximum-matching',
        ],
      },
    ],
  },
  {
    id: 'exact-geometry',
    title: '精确整数计算几何',
    description: '用精确叉积处理方向、触碰、边界、面积和凸包退化情况。',
    level: '进阶',
    estimatedDays: 10,
    chapters: [
      {
        title: '方向与边界',
        description: '禁止使用浮点误差猜测整数几何的符号。',
        problemIds: ['point-orientation', 'segment-intersection', 'polygon-double-area', 'point-in-polygon'],
      },
      {
        title: '坐标变换与外轮廓',
        description: '理解距离极差与单调链删除规则。',
        problemIds: ['maximum-manhattan', 'convex-hull-vertices'],
      },
    ],
  },
);
